### ISSUE TITLE
Running tests fails

### ISSUE THREAD

**Issue by martinling** [greatscottgadgets/facedancer#123]
Following the instructions in `test/README.md`, I can start the test device with `python -m test.device`, but running `python -m unittest` from the repository root results in:

```
(venv) martin@nomad:~/repos/facedancer$ python -m unittest 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3.12/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/usr/lib/python3.12/unittest/main.py", line 104, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.12/unittest/main.py", line 136, in parseArgs
    self._do_discovery([])
  File "/usr/lib/python3.12/unittest/main.py", line 253, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/usr/lib/python3.12/unittest/main.py", line 160, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/unittest/loader.py", line 310, in discover
    tests = list(self._find_tests(start_dir, pattern))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/unittest/loader.py", line 366, in _find_tests
    tests, should_recurse = self._find_test_path(full_path, pattern)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/unittest/loader.py", line 418, in _find_test_path
    raise ImportError(
ImportError: 'test' module incorrectly imported from '/home/martin/repos/facedancer/test'. Expected '/home/martin/repos/facedancer'. Is this module globally installed?
```

Same result on both Python 3.11 and 3.12.

**Comment by martinling** [comment]
Oops, this one was my fault. I had a local `test.py` file that was confusing it.
