### ISSUE TITLE
HID Mouse stuck at 125 Hz + Crashing @ 1000 Hz

### ISSUE THREAD

**Issue by gionetti** [greatscottgadgets/Facedancer#62]
I wrote a simple HID mouse class for Facedancer. The basic functionality works as expected. 

**Issue:**
Regardless of the devices `bInterval` setting, the device seems to be stuck at a max of 125 Hz (60 Hz on average) 
Tested using https://devicetests.com/mouse-rate-test

Any interval below 4ms will cause an error shortly after EP1 is configured. 

What is my best strategy for debugging this? Is my device configuration causing the issue, such as a missing IN or OUT handler?

**Here is my HID class and the stack trace for reference:**
```
from .                        import default_main

from ..future                 import *
from ..classes.hid.usage      import *
from ..classes.hid.descriptor import *
from ..classes.hid.mouse      import *
from ..classes                import USBDeviceClass

@use_inner_classes_automatically
class USBMouseDevice(USBDevice):
    """ Simple USB mouse device. """
    name                     : str   = "Wired Mouse"
    device_class             : int   = 0
    device_subclass          : int   = 0
    protocol_revision_number : int   = 0
    max_packet_size_ep0      : int   = 64
    vendor_id                : int   = 0x1234 
    product_id               : int   = 0x5678
    manufacturer_string      : str   = "Company, Inc."
    product_string           : str   = "ABC Mouse"
    serial_number_string     : str   = "12345678"
    supported_languages      : tuple = (LanguageIDs.ENGLISH_US,)
    device_revision          : int   = 0
    usb_spec_version         : int   = 0x0002

    class MouseConfiguration(USBConfiguration):
        """ Primary USB configuration: act as a mouse. """
        number                 : int    = 1
        configuration_string   : str    = None
        max_power              : int    = 500
        self_powered           : bool   = True
        supports_remote_wakeup : bool   = True

        class MouseInterface(USBInterface):
            """ Core HID interface for our mouse. """
            name                   : str = "USB mouse interface"
            number                 : int = 0
            alternate              : int = 0
            class_number           : int = USBDeviceClass.HID
            subclass_number        : int = 0
            protocol_number        : int = 0
            interface_string       : str = None

            class MouseEventEndpoint(USBEndpoint):
                number               : int                    = 1
                direction            : USBDirection           = USBDirection.IN
                transfer_type        : USBTransferType        = USBTransferType.INTERRUPT
                synchronization_type : USBSynchronizationType = USBSynchronizationType.NONE
                usage_type           : USBUsageType           = USBUsageType.DATA
                max_packet_size      : int                    = 64
                interval             : int                    = 4

            class USBClassDescriptor(USBClassDescriptor):
                number      : int   =  USBDescriptorTypeNumber.HID
                raw         : bytes = b'\x09\x21\x10\x01\x00\x01\x22\x3A\x00'
                # bLength = 0x09 = 9 bytes
                # bDescriptorType = 0x21 = 33 = HID
                # bcdHID = 0x0110 = 1.1 HID spec release version (little endian)
                # bCountryCode = 0x00 = Not Supported
                # bNumDescriptors = 0x01
                # bDescriptorType = 0x22 = 34 = REPORT
                # wDescriptorLength = 0x003A = 58 = total size (bytes) of the Report descriptor (little endian)

            class ReportDescriptor(HIDReportDescriptor):
                number : int    = USBDescriptorTypeNumber.REPORT
                fields : tuple = (
                    USAGE_PAGE       (HIDUsagePage.GENERIC_DESKTOP),
                    USAGE            (HIDGenericDesktopUsage.MOUSE),
                    COLLECTION       (HIDCollection.APPLICATION),
                        USAGE            (HIDGenericDesktopUsage.POINTER),
                        COLLECTION       (HIDCollection.PHYSICAL),

                            USAGE_PAGE       (HIDUsagePage.BUTTONS),
                            USAGE_MINIMUM    (0x01),
                            USAGE_MAXIMUM    (0x03),
                            LOGICAL_MINIMUM  (0x00),
                            LOGICAL_MAXIMUM  (0x01),
                            REPORT_COUNT     (0x03),
                            REPORT_SIZE      (0x01),
                            INPUT            (variable=True),
                            REPORT_COUNT     (0x01),
                            REPORT_SIZE      (0x05),
                            INPUT            (constant=True, variable=True),

                            # One byte of constant zero-padding.
                            # This is required for compliance; and Windows will ignore this report
                            # if the zero byte isn't present.
                            REPORT_COUNT     (0x01),
                            REPORT_SIZE      (0x08),
                            INPUT            (constant=True, variable=True),
                            
                            USAGE_PAGE       (HIDUsagePage.GENERIC_DESKTOP),
                            USAGE            (HIDGenericDesktopUsage.X),
                            USAGE            (HIDGenericDesktopUsage.Y),
                            LOGICAL_MINIMUM  (0x00, 0x80), # logic min (-32768)
                            LOGICAL_MAXIMUM  (0xff, 0x7f), # logic max (32767)
                            REPORT_SIZE      (0x10),
                            REPORT_COUNT     (0x02),
                            INPUT            (variable=True, relative=True),
                        END_COLLECTION   (),
                    END_COLLECTION   (),
                )

            @class_request_handler(number=USBStandardRequests.GET_INTERFACE)
            @to_this_interface
            def handle_get_interface_request(self, request):
                # Silently stall GET_INTERFACE class requests.
                request.stall()

    def __post_init__(self):
        super().__post_init__()
        self.buttons = MouseButtons.NONE
        self.dx = 0
        self.dy = 0

    def getUnsigned(self, val):
        return val + MouseLogicalRange.UNSIGNED_MAX if val < 0 else val

    def getPendingMove(self):
        x, y = self.getUnsigned(self.dx), self.getUnsigned(self.dy)
        self.dx = 0
        self.dy = 0
        return x, y

    def _generate_hid_report(self) -> bytes:
        """ Generates a single HID report for the given mouse state. """
        dx, dy = self.getPendingMove()
        dx_upper = (dx >> 8) & 0xFF
        dx_lower = (dx) & 0xFF
        dy_upper = (dy >> 8) & 0xFF
        dy_lower = (dy) & 0xFF
        return bytes([self.buttons, 0x00, dx_lower, dx_upper, dy_lower, dy_upper])

    def handle_data_requested(self, endpoint: USBEndpoint):
        """ Provide data once per host request. """
        report = self._generate_hid_report()
        endpoint.send(report)

    #
    # User-facing API.
    #

    def button_down(self, code: MouseButtons):
        """ Marks a given button as pressed """
        self.buttons |= code

    def button_up(self, code: MouseButtons):
        """ Marks a given button as released """
        self.buttons &= ~code

    def addToPendingMove(self, dx: int = 0, dy: int = 0):
        self.dx += dx
        self.dy += dy

    def all_buttons_up(self):
        """ Releases all buttons currently pressed. """
        self.buttons = MouseButtons.NONE

if __name__ == "__main__":
    default_main(USBMouseDevice)
```

**Stack trace when running a basic example with EP1 at 1ms bInterval**

```
python .\Facedancer\examples\rubber-jerry.py

INFO    | goodfet        | Skipping GoodFET-based devices, as pyserial isn't installed.
INFO    | greatdancer    | Connecting to host.
INFO    | rubber-jerry   | Beginning mouse demo...
INFO    | device         | Host issued a bus reset; resetting our connection.
INFO    | device         | Host issued a bus reset; resetting our connection.
INFO    | greatdancer    | Configuring endpoint 01/IN: INTERRUPT transfers every 1ms.
INFO    | greatdancer    | Disconnecting from host.

Traceback (most recent call last):
  File ".\Facedancer\examples\rubber-jerry.py", line 78, in <module>
    main(device, testMouse())
  File "D:\Anaconda3\lib\site-packages\facedancer\devices\__init__.py", line 51, in default_main
    device.emulate(*coroutines)
  File "D:\Anaconda3\lib\site-packages\facedancer\future\device.py", line 175, in emulate
    self.run_with(*coroutines)
  File "D:\Anaconda3\lib\site-packages\facedancer\future\device.py", line 160, in run_with
    asyncio.run(inner())
  File "D:\Anaconda3\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "D:\Anaconda3\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "D:\Anaconda3\lib\site-packages\facedancer\future\device.py", line 158, in inner
    await asyncio.gather(self.run(), *coroutines)
  File "D:\Anaconda3\lib\site-packages\facedancer\future\device.py", line 147, in run
    self.backend.service_irqs()
  File "D:\Anaconda3\lib\site-packages\facedancer\backends\greatdancer.py", line 772, in service_irqs
    self._handle_nak_events()
  File "D:\Anaconda3\lib\site-packages\facedancer\backends\greatdancer.py", line 714, in _handle_nak_events
    self.connected_device.handle_nak(endpoint.number)
  File "D:\Anaconda3\lib\site-packages\facedancer\future\device.py", line 291, in handle_nak
    self.handle_data_requested(endpoint)
  File "D:\Anaconda3\lib\site-packages\facedancer\devices\mouse.py", line 167, in handle_data_requested
    endpoint.send(report)
  File "D:\Anaconda3\lib\site-packages\facedancer\future\endpoint.py", line 78, in send
    packet_size=self.max_packet_size, blocking=blocking)
  File "D:\Anaconda3\lib\site-packages\facedancer\future\device.py", line 251, in _send_in_packets
    self.backend.send_on_endpoint(endpoint_number, packet, blocking=blocking)
  File "D:\Anaconda3\lib\site-packages\facedancer\backends\greatdancer.py", line 246, in send_on_endpoint
    self.api.send_on_endpoint(ep_num, bytes(data))
  File "D:\Anaconda3\lib\site-packages\pygreat\comms.py", line 1109, in method
    timeout=timeout, max_response_length=max_response_length, encoding=encoding, *arguments)
  File "D:\Anaconda3\lib\site-packages\pygreat\comms.py", line 1264, in execute_command
    out_format, *arguments, **kwargs)
  File "D:\Anaconda3\lib\site-packages\pygreat\comms.py", line 771, in execute_command
    None, max_response_length, comms_timeout, pretty_name, rephrase_errors)
  File "D:\Anaconda3\lib\site-packages\pygreat\comms_backends\usb.py", line 353, in execute_raw_command
    self.LIBGREAT_REQUEST_NUMBER, self.LIBGREAT_VALUE_EXECUTE, flags, to_send, timeout)
  File "D:\Anaconda3\lib\site-packages\usb\core.py", line 1089, in ctrl_transfer
    self.__get_timeout(timeout))
  File "D:\Anaconda3\lib\site-packages\usb\backend\libusb0.py", line 609, in ctrl_transfer
    timeout
  File "D:\Anaconda3\lib\site-packages\usb\backend\libusb0.py", line 447, in _check
    raise USBError(errmsg, ret)
usb.core.USBError: [Errno None] b'libusb0-dll:err [control_msg] sending control message failed, win error: A device attached to the system is not functioning.\r\n\n'
```

**Comment by martinling** [comment]
This doesn't seem surprising to me.

Each time the target host polls your mouse for a report, the firmware running on the GreatFET has to send a request back to the control host. It can't do that instantly - it has to wait for the control host to poll it for data. The control host has to see that request and execute your `handle_data_requested` method. Then the result gets sent back to the GreatFET, which can then respond to the the target host. This round trip happens every time the target host polls your mouse for a report, and takes a few milliseconds.

The GreatFET itself should be able to handle sending reports at 1000Hz, but only if it has them ready to send. To hit that rate, you'd need to arrange things such that the control host is sending its reports to the GreatFET in advance, and the GreatFET is sending reports one at a time from a queue. I expect that would require some changes to Facedancer.

**Comment by gionetti** [comment]
First off, @martinling thank you for taking time to explain to me the reason for the observed frequency. This really helped me understand where my problem was. Also, cloning the firmware repo, facedancer repo, and reading the basics on https://www.beyondlogic.org/usbnutshell/usb1.shtml was really crucial for me to understand how this emulation is happening and how USB works in general.

I have partially solved my problem without touching the firmware of the device. 

1) The `handle_data_requested` has been replaced with the 'handle_buffer_empty'. This increased the frequency that device could send packets to target host by a factor of 2 roughly as we are no longer waiting for the NAK interrupt that the device raises. We operate when the device has an empty buffer ready to accept new DATA for target host to read. (Host polls are not missing)

2) the `endpoint.send()` method has been replaced by a custom method that uses assumptions about how this HID device functions to improve directness and speed

3) the IRQ routine for greatdancer.py has been modified to prioritize EP1 IN (specific to this use case)

4) the SetPriorityClass and SetThreadPriority methods from win32 have been used to request that the process and threads are given higher scheduling priority from an OS perspective

Overall I have achieved a frequency of 500Hz and the device no longer crashes (due to timeout) when host is polling at 1ms interval. To go beyond this, modifications to the usb_queue and IRQ handlers in the firmware would need to be made as you mentioned in your comment. If the DATA for the interrupt endpoint is already on the device and ready to send to host frequencies of 1000Hz+ could be achieved.
